#!/bin/bash

# Coturn STUN/TURN Server Setup Script
# This script helps set up Coturn for development and production

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration variables
TURN_SECRET_KEY=""
TURN_REALM="unitalks"
TURN_PUBLIC_IP=""
DOMAIN_NAME=""

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Generate random secret key
generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        # Fallback method
        date +%s | sha256sum | base64 | head -c 32
    fi
}

# Get public IP
get_public_ip() {
    # Try multiple services
    local services=(
        "https://api.ipify.org"
        "https://ipinfo.io/ip"
        "https://icanhazip.com"
        "https://ifconfig.me"
    )
    
    for service in "${services[@]}"; do
        local ip=$(curl -s "$service" 2>/dev/null)
        if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "$ip"
            return 0
        fi
    done
    
    return 1
}

# Install Coturn
install_coturn() {
    log_info "Installing Coturn..."
    
    if command -v apt-get >/dev/null 2>&1; then
        # Ubuntu/Debian
        sudo apt-get update
        sudo apt-get install -y coturn
    elif command -v yum >/dev/null 2>&1; then
        # CentOS/RHEL
        sudo yum install -y coturn
    elif command -v dnf >/dev/null 2>&1; then
        # Fedora
        sudo dnf install -y coturn
    else
        log_error "Unsupported package manager. Please install Coturn manually."
        exit 1
    fi
    
    log_info "Coturn installed successfully"
}

# Setup configuration
setup_config() {
    log_info "Setting up Coturn configuration..."
    
    # Generate secret key if not provided
    if [[ -z "$TURN_SECRET_KEY" ]]; then
        TURN_SECRET_KEY=$(generate_secret)
        log_info "Generated secret key: ${TURN_SECRET_KEY:0:8}..."
    fi
    
    # Get public IP if not provided
    if [[ -z "$TURN_PUBLIC_IP" ]]; then
        TURN_PUBLIC_IP=$(get_public_ip)
        if [[ $? -eq 0 ]]; then
            log_info "Detected public IP: $TURN_PUBLIC_IP"
        else
            log_warn "Could not detect public IP automatically"
            read -p "Enter your public IP address: " TURN_PUBLIC_IP
        fi
    fi
    
    # Create configuration file
    local config_file="/etc/coturn/turnserver.conf"
    local backup_file="/etc/coturn/turnserver.conf.backup"
    
    # Backup existing configuration
    if [[ -f "$config_file" ]]; then
        sudo cp "$config_file" "$backup_file"
        log_info "Backed up existing configuration to $backup_file"
    fi
    
    # Create new configuration
    sudo tee "$config_file" > /dev/null <<EOF
# Coturn STUN/TURN Server Configuration
# Generated by setup script on $(date)

# Network configuration
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=$TURN_PUBLIC_IP

# Authentication
use-auth-secret
static-auth-secret=$TURN_SECRET_KEY
realm=$TURN_REALM
max-session-lifetime=86400000

# Transport protocols
udp-enabled=true
tcp-enabled=true
tls-enabled=true
dtls-enabled=true

# TURN relay configuration
total-quota=100
user-quota=12
max-bps=64000

# Security settings
no-multicast-peers
no-loopback-peers
stale-nonce=600
max-allocate-lifetime=3600000

# Logging
log-file=/var/log/turnserver.log
verbose
syslog

# Performance
max-connections=1000
thread-pool-size=4

# Mobile and NAT traversal
rtp-timeout-udp=120
rtp-timeout-tcp=300
EOF

    log_info "Configuration created at $config_file"
}

# Setup firewall
setup_firewall() {
    log_info "Configuring firewall..."
    
    if command -v ufw >/dev/null 2>&1; then
        # Ubuntu Firewall
        sudo ufw allow 3478/udp
        sudo ufw allow 3478/tcp
        sudo ufw allow 5349/tcp
        sudo ufw allow 49152:65535/udp
        log_info "UFW firewall rules added"
    elif command -v firewall-cmd >/dev/null 2>&1; then
        # CentOS/RHEL Firewall
        sudo firewall-cmd --permanent --add-port=3478/udp
        sudo firewall-cmd --permanent --add-port=3478/tcp
        sudo firewall-cmd --permanent --add-port=5349/tcp
        sudo firewall-cmd --permanent --add-port=49152-65535/udp
        sudo firewall-cmd --reload
        log_info "Firewalld rules added"
    else
        log_warn "Could not configure firewall automatically"
        log_warn "Please manually open ports: 3478/udp, 3478/tcp, 5349/tcp, 49152-65535/udp"
    fi
}

# Setup SSL certificates
setup_ssl() {
    log_info "Setting up SSL certificates..."
    
    local cert_dir="/etc/coturn/certs"
    sudo mkdir -p "$cert_dir"
    
    if [[ -n "$DOMAIN_NAME" ]]; then
        # Use Let's Encrypt
        if command -v certbot >/dev/null 2>&1; then
            log_info "Using Let's Encrypt for $DOMAIN_NAME"
            sudo certbot certonly --standalone -d "$DOMAIN_NAME"
            sudo ln -sf "/etc/letsencrypt/live/$DOMAIN_NAME/fullchain.pem" "$cert_dir/cert.pem"
            sudo ln -sf "/etc/letsencrypt/live/$DOMAIN_NAME/privkey.pem" "$cert_dir/private.key"
        else
            log_warn "Certbot not found. Please install SSL certificates manually."
        fi
    else
        # Generate self-signed certificate
        log_info "Generating self-signed certificate"
        sudo openssl req -x509 -newkey rsa:4096 -keyout "$cert_dir/private.key" -out "$cert_dir/cert.pem" -days 365 -nodes -subj "/CN=$TURN_PUBLIC_IP"
    fi
    
    # Update configuration with SSL paths
    sudo tee -a "/etc/coturn/turnserver.conf" > /dev/null <<EOF

# SSL/TLS configuration
cert=$cert_dir/cert.pem
pkey=$cert_dir/private.key
EOF
}

# Start and enable service
start_service() {
    log_info "Starting Coturn service..."
    
    if command -v systemctl >/dev/null 2>&1; then
        sudo systemctl restart coturn
        sudo systemctl enable coturn
        
        # Check status
        if sudo systemctl is-active --quiet coturn; then
            log_info "Coturn service is running"
        else
            log_error "Failed to start Coturn service"
            sudo systemctl status coturn
            exit 1
        fi
    else
        log_warn "Could not start service automatically"
        log_warn "Please start Coturn manually"
    fi
}

# Test configuration
test_config() {
    log_info "Testing Coturn configuration..."
    
    # Wait for service to start
    sleep 3
    
    # Test basic connectivity
    if nc -z -v -w 2 localhost 3478 2>/dev/null; then
        log_info "✓ Coturn is responding on port 3478"
    else
        log_error "✗ Coturn is not responding on port 3478"
        return 1
    fi
    
    # Test TURN server
    if command -v turnutils_uclient >/dev/null 2>&1; then
        log_info "Testing TURN server functionality..."
        echo "test" | turnutils_uclient -T -u test -w test "$TURN_PUBLIC_IP" 2>/dev/null && \
            log_info "✓ TURN server test passed" || \
            log_warn "⚠ TURN server test failed (may need additional configuration)"
    else
        log_warn "turnutils_uclient not available for testing"
    fi
}

# Generate environment file
generate_env() {
    log_info "Generating environment file..."
    
    local env_file=".env"
    local turn_url="turn:$TURN_PUBLIC_IP:3478"
    
    if [[ -n "$DOMAIN_NAME" ]]; then
        turn_url="turn:$DOMAIN_NAME:3478"
    fi
    
    cat > "$env_file" <<EOF
# Coturn STUN/TURN Server Configuration
# Generated by setup script on $(date)

# Server Configuration
NODE_ENV=development
PORT=5002
SOCKET_URL=http://localhost:5002

# Coturn TURN Server Configuration
TURN_SERVER_URL=$turn_url
TURN_SECRET_KEY=$TURN_SECRET_KEY
TURN_REALM=$TURN_REALM
TURN_CREDENTIAL_TTL=3600
TURN_PUBLIC_IP=$TURN_PUBLIC_IP

# STUN Server Configuration (fallback)
STUN_SERVER_URL=stun:stun.l.google.com:19302

# Security Settings
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
FORCE_HTTPS=false

# Support Email Configuration (optional)
SUPPORT_TO=
SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
EOF

    log_info "Environment file created: $env_file"
    log_warn "Please review and update the environment file as needed"
}

# Main function
main() {
    log_info "Coturn STUN/TURN Server Setup Script"
    log_info "====================================="
    
    # Check if running with sudo privileges
    if [[ $EUID -ne 0 ]]; then
        log_error "This script requires sudo privileges"
        log_error "Run with sudo: sudo ./setup-coturn.sh"
        exit 1
    fi
    
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --secret)
                TURN_SECRET_KEY="$2"
                shift 2
                ;;
            --realm)
                TURN_REALM="$2"
                shift 2
                ;;
            --ip)
                TURN_PUBLIC_IP="$2"
                shift 2
                ;;
            --domain)
                DOMAIN_NAME="$2"
                shift 2
                ;;
            --help)
                echo "Usage: $0 [OPTIONS]"
                echo "Options:"
                echo "  --secret KEY    Secret key for TURN authentication"
                echo "  --realm REALM    Authentication realm (default: unitalks)"
                echo "  --ip IP          Public IP address"
                echo "  --domain DOMAIN  Domain name for SSL certificates"
                echo "  --help           Show this help message"
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
    
    # Confirm installation
    echo
    log_info "This script will:"
    echo "  1. Install Coturn STUN/TURN server"
    echo "  2. Configure firewall rules"
    echo "  3. Setup SSL certificates"
    echo "  4. Generate environment configuration"
    echo
    read -p "Continue? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Installation cancelled"
        exit 0
    fi
    
    # Run installation steps
    install_coturn
    setup_config
    setup_firewall
    setup_ssl
    start_service
    
    if test_config; then
        generate_env
        
        echo
        log_info "🎉 Coturn setup completed successfully!"
        echo
        log_info "Configuration summary:"
        echo "  • Public IP: $TURN_PUBLIC_IP"
        echo "  • Realm: $TURN_REALM"
        echo "  • Secret key: ${TURN_SECRET_KEY:0:8}..."
        echo "  • Environment file: .env"
        echo
        log_info "Next steps:"
        echo "  1. Review the generated .env file"
        echo "  2. Start your application server"
        echo "  3. Test WebRTC connections"
        echo
        log_warn "Important:"
        echo "  • Keep your secret key secure!"
        echo "  • Configure proper SSL certificates for production"
        echo "  • Monitor server logs for issues"
    else
        log_error "Setup completed with errors. Please check the logs."
        exit 1
    fi
}

# Run main function
main "$@"
